# Generated by Django 5.2.8 on 2026-01-13 12:36

import apps.students.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_logbook_logbookentry_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, null=True)),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='company_docs/')),
                ('registration_body', models.CharField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='placement_letter',
            field=models.FileField(blank=True, null=True, upload_to=apps.students.utils.placement_letter_upload_path),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='max_students',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='studentinstitutionprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='placement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.company'),
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
