# Generated by Django 5.2.8 on 2026-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_supervisorprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
