# Generated by Django 5.2.8 on 2026-01-13 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_supervisorprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
